SELECT * FROM financial_loan

--- 1. TOTAL LOAN APPLICATIONS

SELECT COUNT(ID) FROM financial_loan

---2.MTD TOTAL LOAN APPLICATIONS

SELECT COUNT(ID) AS MTD_TOTAL_LOAN_APPLICATIONS FROM financial_loan
WHERE MONTH(ISSUE_DATE) =12 AND YEAR(ISSUE_DATE)=2021

---3.PMTD TOTAL LOAN APPLICATIONS
SELECT COUNT(ID) AS PMTD_TOTAL_LOAN_APPLICATIONS FROM financial_loan
WHERE MONTH(ISSUE_DATE) =11 AND YEAR(ISSUE_DATE)=2021

---4. TOTAL FUNDED AMOUNT

SELECT SUM(LOAN_AMOUNT) AS TOAL_FUNDED_AMOUNT FROM financial_loan

---5. MTD_TOTAL FUNDED AMOUNT

SELECT SUM(LOAN_AMOUNT) AS MTD_TOAL_FUNDED_AMOUNT FROM financial_loan
WHERE MONTH(ISSUE_DATE) =12 AND YEAR(ISSUE_DATE)=2021

---6. PMTD_TOTAL FUNDED AMOUNT

SELECT SUM(LOAN_AMOUNT) AS PMTD_TOAL_FUNDED_AMOUNT FROM financial_loan
WHERE MONTH(ISSUE_DATE) =11 AND YEAR(ISSUE_DATE)=2021

---7.TOTAL AMOUNT RECEIVED

SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED FROM financial_loan

---8.MTD TOTAL AMOUNT RECEIVED

SELECT SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECEIVED FROM financial_loan
WHERE MONTH(ISSUE_DATE) =12 AND YEAR(ISSUE_DATE)=2021

---9. AVG INTEREST RATE
SELECT ROUND(AVG(INT_RATE),4)*100 AS AVG_INTEREST_RATE FROM financial_loan

---10. AVG DTI
 SELECT ROUND(AVG(DTI),4)*100 AS AVG_DTI FROM financial_loan

 --- GOOD LOAN PERCENTAGE
  SELECT(COUNT(CASE WHEN LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current' THEN ID END)*100)/
  COUNT(ID) AS GOOD_LOAN_STATUS
  FROM financial_loan


  -- GOOD LOAN APPLICATIONS

  SELECT COUNT(ID) AS GOOD_LOAN_APPLICATIONS FROM financial_loan
  WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'CURRENT'

  ---GOOD LOAN FUNDED AMOUNT

  SELECT SUM(loan_amount) AS GOOD_LOAN_FUNDED_AMOUNT FROM financial_loan
  WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'CURRENT'

  ---GOOD LOAN TOTAL AMOUNT RECEIVED

  SELECT SUM(total_payment) AS GOOD_LOAN_AMOUNT_RECEIVED FROM financial_loan
  WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'CURRENT'


--- BAD LOAN PERCENTAGE
  SELECT(COUNT(CASE WHEN LOAN_STATUS = 'Charged Off' THEN ID END)*100)/
  COUNT(ID) AS BAD_LOAN_PERCENTAGE
  FROM financial_loan


  -- BAD LOAN APPLICATIONS

  SELECT COUNT(ID) AS BAD_LOAN_APPLICATIONS FROM financial_loan
  WHERE LOAN_STATUS = 'Charged Off'

  ---BAD LOAN FUNDED AMOUNT

  SELECT SUM(loan_amount) AS BAD_LOAN_FUNDED_AMOUNT FROM financial_loan
  WHERE LOAN_STATUS = 'Charged Off'

  ---BAD LOAN TOTAL AMOUNT RECEIVED

  SELECT SUM(total_payment) AS _LOAN_AMOUNT_RECEIVED FROM financial_loan
  WHERE LOAN_STATUS = 'Charged Off'


