SELECT * FROM PIZZA_SALES

----1.TOTAL REVENUE

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES

---2.AVERAGE ORDER VALUE

SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID) AS AVERAGE_ORDER_VALUE FROM PIZZA_SALES

---3.TOTAL PIZZAS SOLD

SELECT SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD FROM PIZZA_SALES

---4. TOTAL ORDERS

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES

---5.AVERAGE PIZZAS PER ORDER

SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AVG_PIZZAS_PER_ORDER
FROM PIZZA_SALES


---6.DAILY TREND FOR TOTAL ORDERS

SELECT DATENAME(DW,ORDER_DATE) AS ORDER_DAY,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY DATENAME(DW,ORDER_DATE)

---7.HOURLY TREND FOR TOTAL ORDERS

SELECT DATEPART(HOUR,ORDER_TIME) AS ORDER_HOURS,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY DATEPART(HOUR,ORDER_TIME)
ORDER BY DATEPART(HOUR,ORDER_TIME)

---8.PERCENTAGE OF SALES PIZZA CATEGORY

SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE)*100/
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY

---9. PERCENTAGE OF SALES BY PIZZA_SIZE

SELECT PIZZA_SIZE, CAST(SUM(total_price) AS DECIMAL(10,2)) as total_revenue,
CAST(SUM(total_price) * 100 / (SELECT SUM(total_price) from pizza_sales) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE
ORDER BY PIZZA_SIZE

---10. TOP 5 BEST SELLERS BY PIZZAS SOLD

SELECT Top 5 PIZZA_NAME, SUM(quantity) AS Total_Pizza_Sold
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY Total_Pizza_Sold DESC

---11. BOTTOM 5 BEST SELLERS BY PIZZAS SOLD

SELECT Top 5 PIZZA_NAME, SUM(quantity) AS Total_Pizza_Sold
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY Total_Pizza_Sold ASC


